backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "works"
    label: "Works"
    folder: "src/pages/works"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/essay/index.md"
        label: "Essay"
        name: "essay"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "essay-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/exhibition/index.md"
        label: "Exhibition"
        name: "exhibition"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "essay-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/speciation/index.md"
        label: "Speciation"
        name: "speciation"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "speciation-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Artist", name: "artist", widget: "string" }
          - { label: "Artist Statement", name: "statement", widget: "string" }
          - { label: "Artist Bio + Links", name: "bio", widget: "string" }
          - { label: "Link 1 Title", name: "link1title", widget: "string" }
          - { label: "Link 1 Link", name: "link1link", widget: "string" }
          - { label: "Link 2 Title", name: "link2title", widget: "string" }
          - { label: "Link 2 Link", name: "link2link", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "src/pages/zoom-princess/index.md"
        label: "Zoom Princess"
        name: "zoom princess"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "zoom-princess-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Artist", name: "artist", widget: "string" }
          - { label: "Artist Statement", name: "statement", widget: "string" }
          - { label: "Artist Bio + Links", name: "bio", widget: "string" }
          - { label: "Link 1 Title", name: "link1title", widget: "string" }
          - { label: "Link 1 Link", name: "link1link", widget: "string" }
          - { label: "Link 2 Title", name: "link2title", widget: "string" }
          - { label: "Link 2 Link", name: "link2link", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "src/pages/antechamber/index.md"
        label: "Antechamber"
        name: "antechamber"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "antechamber-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Artist", name: "artist", widget: "string" }
          - { label: "Artist Statement", name: "statement", widget: "string" }
          - { label: "Artist Bio + Links", name: "bio", widget: "string" }
          - { label: "Link 1 Title", name: "link1title", widget: "string" }
          - { label: "Link 1 Link", name: "link1link", widget: "string" }
          - { label: "Link 2 Title", name: "link2title", widget: "string" }
          - { label: "Link 2 Link", name: "link2link", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "src/pages/pac-tracer/index.md"
        label: "Pac Tracer"
        name: "pac tracer"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "antechamber-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Artist", name: "artist", widget: "string" }
          - { label: "Artist Statement", name: "statement", widget: "string" }
          - { label: "Artist Bio + Links", name: "bio", widget: "string" }
          - { label: "Link 1 Title", name: "link1title", widget: "string" }
          - { label: "Link 1 Link", name: "link1link", widget: "string" }
          - { label: "Link 2 Title", name: "link2title", widget: "string" }
          - { label: "Link 2 Link", name: "link2link", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "src/pages/arcadia-inc/index.md"
        label: "Arcadia Inc"
        name: "arcadia inc"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "arcadia-inc-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Artist", name: "artist", widget: "string" }
          - { label: "Artist Statement", name: "statement", widget: "string" }
          - { label: "Artist Bio + Links", name: "bio", widget: "string" }
          - { label: "Link 1 Title", name: "link1title", widget: "string" }
          - { label: "Link 1 Link", name: "link1link", widget: "string" }
          - { label: "Link 2 Title", name: "link2title", widget: "string" }
          - { label: "Link 2 Link", name: "link2link", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }      
      - file: "src/pages/events/index.md"
        label: "Events Page"
        name: "events"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "events-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Location, name: location, widget: string },
                        { label: Link, name: link, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
